# Generated by Django 5.0 on 2025-08-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_service_alter_generalinfo_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_count', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('user_job', models.CharField(max_length=50)),
                ('review', models.TextField()),
            ],
        ),
    ]
