# Generated by Django 5.0 on 2025-10-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='author',
        ),
    ]
